#!/usr/perl5/5.22.0/bin/perl

use strict;
use warnings;

use IO::File;

my $rand_fh  = IO::File->new("/dev/urandom","<") or die "unable to open /dev/urandom";
my $fw_fh = IO::File->new("/tmp/file_writer-junk.out",">") or 
  die "Unable to open /tmp/file_writer-junk.out";

# Unbuffered writes
$fw_fh->autoflush(1);

while (1) {
  sleep(1);
  my ($buf);
  read($rand_fh, $buf, 8192);
  $fw_fh->write($buf,8192);
}
